name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs:
      - package
    env:
      VERSION: dev
      KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_DEV }}
      KUBECONFIG: kubeconfig
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Get kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
          chmod +x kubectl

      - name: Save kubeconfig
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_DEV }}
        run: |
          echo ${KUBECONFIG_FILE} | base64 -d  > ${KUBECONFIG}

      - name: Apply deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          ./kubectl apply -f manifests/haproxy-ingress-manifests.yaml
